name: letsencrypt-esxi-dns

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Create VIB
        run: /bin/bash ./build/build.sh

      - name: Store VIB
        uses: actions/upload-artifact@v7
        with:
          name: letsencrypt-esxi-dns
          path: |
            artifacts/letsencrypt-esxi-dns.vib
            artifacts/letsencrypt-esxi-dns-offline-bundle.zip
          if-no-files-found: error

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve build artifacts
        uses: actions/download-artifact@v8
        with:
          name: letsencrypt-esxi-dns

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: letsencrypt-esxi-dns
          files: |
            letsencrypt-esxi-dns.vib
            letsencrypt-esxi-dns-offline-bundle.zip
